### ISSUE TITLE
Build script fails on Ubuntu 12.04

### ISSUE THREAD

**Issue by thanasik** [arturadib/node-qt#38]
I've been wanting to try this out for a while, and I got to it today. I used the example code in the README, ran a quick `npm install node-qt` and I get an error saying that the build script fails, among other things. Any ideas why this is? Thanks in advance.

```
-
> node-qt@0.0.2 install /home/karysto/Desktop/qtNodeExample/node_modules/node-qt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtCore' found
Package QtGui was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtGui.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtGui' found
Package QtTest was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtTest.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtTest' found
gyp: Call to 'pkg-config --libs-only-l QtCore QtGui QtTest' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-77-generic-pae
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/karysto/Desktop/qtNodeExample/node_modules/node-qt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.2.0-77-generic-pae
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-qt"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-qt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-qt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/karysto/Desktop/qtNodeExample/npm-debug.log
```

**Comment by thanasik** [comment]
Should also mention that I also retried it by installing directly from the source repo here on Github, and it still responds with the same script failure.

**Comment by jas0n1ee** [comment]
@karysto pkg-config says you don't have qt-core and other stuffs installed on your ubuntu. After you install qt, try `pkg-config --libs-only-l QtCore QtGui QtTest` and try install node-qt again :).
