### ISSUE TITLE
Fails to install on Kubuntu 16.04 / Node 6.7.0

### ISSUE THREAD

**Issue by teajaymars** [arturadib/node-qt#41]
Followed the instructions & installed the dependencies, this is what happened:

```
osboxes@osboxes:~/dev$ npm install --save node-qt     

> node-qt@0.0.2 install /home/osboxes/dev/node_modules/node-qt
> node-gyp rebuild

make: Entering directory '/home/osboxes/dev/node_modules/node-qt/build'
  CXX(target) Release/obj.target/qt/src/qt.o
../src/qt.cc:30:0: warning: "BUILDING_NODE_EXTENSION" redefined
 #define BUILDING_NODE_EXTENSION
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from ../src/qt.cc:33:0:
../src/QtCore/qsize.h:37:43: error: expected class-name before ‘{’ token
 class QSizeWrap : public node::ObjectWrap {
                                           ^
../src/QtCore/qsize.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtCore/qsize.h:54:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Width(const v8::Arguments& args);
                                                ^
../src/QtCore/qsize.h:55:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Height(const v8::Arguments& args);
                                                 ^
In file included from ../src/qt.cc:34:0:
../src/QtCore/qpointf.h:37:45: error: expected class-name before ‘{’ token
 class QPointFWrap : public node::ObjectWrap {
                                             ^
../src/QtCore/qpointf.h:48:25: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QPointFWrap(const v8::Arguments& args);
                         ^
../src/QtCore/qpointf.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtCore/qpointf.h:54:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> IsNull(const v8::Arguments& args);
                                                 ^
../src/QtCore/qpointf.h:55:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> X(const v8::Arguments& args);
                                            ^
../src/QtCore/qpointf.h:56:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Y(const v8::Arguments& args);
                                            ^
In file included from ../src/qt.cc:36:0:
../src/QtGui/qapplication.h:36:50: error: expected class-name before ‘{’ token
 class QApplicationWrap : public node::ObjectWrap {
                                                  ^
../src/QtGui/qapplication.h:45:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qapplication.h:48:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> ProcessEvents(const v8::Arguments& args);
                                                        ^
../src/QtGui/qapplication.h:49:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Exec(const v8::Arguments& args);
                                               ^
In file included from ../src/qt.cc:37:0:
../src/QtGui/qwidget.h:64:45: error: expected class-name before ‘{’ token
 class QWidgetWrap : public node::ObjectWrap {
                                             ^
../src/QtGui/qwidget.h:73:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qwidget.h:76:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Resize(const v8::Arguments& args);
                                                 ^
../src/QtGui/qwidget.h:77:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Show(const v8::Arguments& args);
                                               ^
../src/QtGui/qwidget.h:78:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Close(const v8::Arguments& args);
                                                ^
../src/QtGui/qwidget.h:79:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Size(const v8::Arguments& args);
                                               ^
../src/QtGui/qwidget.h:80:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Width(const v8::Arguments& args);
                                                ^
../src/QtGui/qwidget.h:81:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Height(const v8::Arguments& args);
                                                 ^
../src/QtGui/qwidget.h:82:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> ObjectName(const v8::Arguments& args);
                                                     ^
../src/QtGui/qwidget.h:83:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetObjectName(const v8::Arguments& args);
                                                        ^
../src/QtGui/qwidget.h:84:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Parent(const v8::Arguments& args);
                                                 ^
../src/QtGui/qwidget.h:85:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Update(const v8::Arguments& args);
                                                 ^
../src/QtGui/qwidget.h:86:59: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetMouseTracking(const v8::Arguments& args);
                                                           ^
../src/QtGui/qwidget.h:87:59: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> HasMouseTracking(const v8::Arguments& args);
                                                           ^
../src/QtGui/qwidget.h:88:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetFocusPolicy(const v8::Arguments& args);
                                                         ^
../src/QtGui/qwidget.h:89:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Move(const v8::Arguments& args);
                                               ^
../src/QtGui/qwidget.h:90:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> X(const v8::Arguments& args);
                                            ^
../src/QtGui/qwidget.h:91:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Y(const v8::Arguments& args);
                                            ^
../src/QtGui/qwidget.h:97:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> PaintEvent(const v8::Arguments& args);
                                                     ^
../src/QtGui/qwidget.h:98:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> MousePressEvent(const v8::Arguments& args);
                                                          ^
../src/QtGui/qwidget.h:99:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> MouseReleaseEvent(const v8::Arguments& args);
                                                            ^
../src/QtGui/qwidget.h:100:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> MouseMoveEvent(const v8::Arguments& args);
                                                         ^
../src/QtGui/qwidget.h:101:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> KeyPressEvent(const v8::Arguments& args);
                                                        ^
../src/QtGui/qwidget.h:102:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> KeyReleaseEvent(const v8::Arguments& args);
                                                          ^
In file included from ../src/qt.cc:38:0:
../src/QtGui/qmouseevent.h:37:49: error: expected class-name before ‘{’ token
 class QMouseEventWrap : public node::ObjectWrap {
                                                 ^
../src/QtGui/qmouseevent.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qmouseevent.h:54:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> X(const v8::Arguments& args);
                                            ^
../src/QtGui/qmouseevent.h:55:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Y(const v8::Arguments& args);
                                            ^
../src/QtGui/qmouseevent.h:56:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Button(const v8::Arguments& args);
                                                 ^
In file included from ../src/qt.cc:39:0:
../src/QtGui/qkeyevent.h:37:47: error: expected class-name before ‘{’ token
 class QKeyEventWrap : public node::ObjectWrap {
                                               ^
../src/QtGui/qkeyevent.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qkeyevent.h:54:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Key(const v8::Arguments& args);
                                              ^
../src/QtGui/qkeyevent.h:55:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Text(const v8::Arguments& args);
                                               ^
In file included from ../src/qt.cc:40:0:
../src/QtGui/qpixmap.h:37:45: error: expected class-name before ‘{’ token
 class QPixmapWrap : public node::ObjectWrap {
                                             ^
../src/QtGui/qpixmap.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qpixmap.h:54:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Width(const v8::Arguments& args);
                                                ^
../src/QtGui/qpixmap.h:55:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Height(const v8::Arguments& args);
                                                 ^
../src/QtGui/qpixmap.h:56:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Save(const v8::Arguments& args);
                                               ^
../src/QtGui/qpixmap.h:57:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Fill(const v8::Arguments& args);
                                               ^
In file included from ../src/qt.cc:41:0:
../src/QtGui/qpainter.h:37:46: error: expected class-name before ‘{’ token
 class QPainterWrap : public node::ObjectWrap {
                                              ^
../src/QtGui/qpainter.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qpainter.h:52:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Begin(const v8::Arguments& args);
                                                ^
../src/QtGui/qpainter.h:53:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> End(const v8::Arguments& args);
                                              ^
../src/QtGui/qpainter.h:54:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> IsActive(const v8::Arguments& args);
                                                   ^
../src/QtGui/qpainter.h:55:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Save(const v8::Arguments& args);
                                               ^
../src/QtGui/qpainter.h:56:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Restore(const v8::Arguments& args);
                                                  ^
../src/QtGui/qpainter.h:59:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetPen(const v8::Arguments& args);
                                                 ^
../src/QtGui/qpainter.h:60:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetFont(const v8::Arguments& args);
                                                  ^
../src/QtGui/qpainter.h:61:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetMatrix(const v8::Arguments& args);
                                                    ^
../src/QtGui/qpainter.h:64:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> FillRect(const v8::Arguments& args);
                                                   ^
../src/QtGui/qpainter.h:65:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> DrawText(const v8::Arguments& args);
                                                   ^
../src/QtGui/qpainter.h:66:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> DrawPixmap(const v8::Arguments& args);
                                                     ^
../src/QtGui/qpainter.h:67:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> DrawImage(const v8::Arguments& args);
                                                    ^
../src/QtGui/qpainter.h:68:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> StrokePath(const v8::Arguments& args);
                                                     ^
In file included from ../src/qt.cc:42:0:
../src/QtGui/qcolor.h:37:44: error: expected class-name before ‘{’ token
 class QColorWrap : public node::ObjectWrap {
                                            ^
../src/QtGui/qcolor.h:43:24: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QColorWrap(const v8::Arguments& args);
                        ^
../src/QtGui/qcolor.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qcolor.h:49:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Red(const v8::Arguments& args);
                                              ^
../src/QtGui/qcolor.h:50:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Green(const v8::Arguments& args);
                                                ^
../src/QtGui/qcolor.h:51:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Blue(const v8::Arguments& args);
                                               ^
../src/QtGui/qcolor.h:52:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Alpha(const v8::Arguments& args);
                                                ^
../src/QtGui/qcolor.h:53:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Name(const v8::Arguments& args);
                                               ^
In file included from ../src/qt.cc:43:0:
../src/QtGui/qbrush.h:37:44: error: expected class-name before ‘{’ token
 class QBrushWrap : public node::ObjectWrap {
                                            ^
../src/QtGui/qbrush.h:43:24: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QBrushWrap(const v8::Arguments& args);
                        ^
../src/QtGui/qbrush.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
In file included from ../src/qt.cc:44:0:
../src/QtGui/qpen.h:37:42: error: expected class-name before ‘{’ token
 class QPenWrap : public node::ObjectWrap {
                                          ^
../src/QtGui/qpen.h:43:22: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QPenWrap(const v8::Arguments& args);
                      ^
../src/QtGui/qpen.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
In file included from ../src/qt.cc:45:0:
../src/QtGui/qimage.h:37:44: error: expected class-name before ‘{’ token
 class QImageWrap : public node::ObjectWrap {
                                            ^
../src/QtGui/qimage.h:43:24: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QImageWrap(const v8::Arguments& args);
                        ^
../src/QtGui/qimage.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qimage.h:49:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> IsNull(const v8::Arguments& args);
                                                 ^
In file included from ../src/qt.cc:46:0:
../src/QtGui/qpainterpath.h:37:50: error: expected class-name before ‘{’ token
 class QPainterPathWrap : public node::ObjectWrap {
                                                  ^
../src/QtGui/qpainterpath.h:43:30: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QPainterPathWrap(const v8::Arguments& args);
                              ^
../src/QtGui/qpainterpath.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qpainterpath.h:49:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> MoveTo(const v8::Arguments& args);
                                                 ^
../src/QtGui/qpainterpath.h:50:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> CurrentPosition(const v8::Arguments& args);
                                                          ^
../src/QtGui/qpainterpath.h:51:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> LineTo(const v8::Arguments& args);
                                                 ^
../src/QtGui/qpainterpath.h:52:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> CloseSubpath(const v8::Arguments& args);
                                                       ^
In file included from ../src/qt.cc:47:0:
../src/QtGui/qfont.h:37:43: error: expected class-name before ‘{’ token
 class QFontWrap : public node::ObjectWrap {
                                           ^
../src/QtGui/qfont.h:48:23: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QFontWrap(const v8::Arguments& args);
                       ^
../src/QtGui/qfont.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qfont.h:54:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetFamily(const v8::Arguments& args);
                                                    ^
../src/QtGui/qfont.h:55:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Family(const v8::Arguments& args);
                                                 ^
../src/QtGui/qfont.h:56:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetPixelSize(const v8::Arguments& args);
                                                       ^
../src/QtGui/qfont.h:57:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> PixelSize(const v8::Arguments& args);
                                                    ^
../src/QtGui/qfont.h:58:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetPointSize(const v8::Arguments& args);
                                                       ^
../src/QtGui/qfont.h:59:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> PointSize(const v8::Arguments& args);
                                                    ^
../src/QtGui/qfont.h:60:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetPointSizeF(const v8::Arguments& args);
                                                        ^
../src/QtGui/qfont.h:61:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> PointSizeF(const v8::Arguments& args);
                                                     ^
In file included from ../src/qt.cc:48:0:
../src/QtGui/qmatrix.h:37:45: error: expected class-name before ‘{’ token
 class QMatrixWrap : public node::ObjectWrap {
                                             ^
../src/QtGui/qmatrix.h:48:25: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QMatrixWrap(const v8::Arguments& args);
                         ^
../src/QtGui/qmatrix.h:51:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qmatrix.h:54:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> M11(const v8::Arguments& args);
                                              ^
../src/QtGui/qmatrix.h:55:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> M12(const v8::Arguments& args);
                                              ^
../src/QtGui/qmatrix.h:56:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> M21(const v8::Arguments& args);
                                              ^
../src/QtGui/qmatrix.h:57:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> M22(const v8::Arguments& args);
                                              ^
../src/QtGui/qmatrix.h:58:45: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Dx(const v8::Arguments& args);
                                             ^
../src/QtGui/qmatrix.h:59:45: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Dy(const v8::Arguments& args);
                                             ^
../src/QtGui/qmatrix.h:60:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Translate(const v8::Arguments& args);
                                                    ^
../src/QtGui/qmatrix.h:61:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Scale(const v8::Arguments& args);
                                                ^
In file included from ../src/qt.cc:49:0:
../src/QtGui/qsound.h:37:44: error: expected class-name before ‘{’ token
 class QSoundWrap : public node::ObjectWrap {
                                            ^
../src/QtGui/qsound.h:43:24: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QSoundWrap(const v8::Arguments& args);
                        ^
../src/QtGui/qsound.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qsound.h:49:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Play(const v8::Arguments& args);
                                               ^
../src/QtGui/qsound.h:50:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> FileName(const v8::Arguments& args);
                                                   ^
../src/QtGui/qsound.h:51:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetLoops(const v8::Arguments& args);
                                                   ^
In file included from ../src/qt.cc:50:0:
../src/QtGui/qscrollarea.h:40:49: error: expected class-name before ‘{’ token
 class QScrollAreaWrap : public node::ObjectWrap {
                                                 ^
../src/QtGui/qscrollarea.h:46:29: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QScrollAreaWrap(const v8::Arguments& args);
                             ^
../src/QtGui/qscrollarea.h:49:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qscrollarea.h:52:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Resize(const v8::Arguments& args);
                                                 ^
../src/QtGui/qscrollarea.h:53:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Show(const v8::Arguments& args);
                                               ^
../src/QtGui/qscrollarea.h:54:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Close(const v8::Arguments& args);
                                                ^
../src/QtGui/qscrollarea.h:55:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Size(const v8::Arguments& args);
                                               ^
../src/QtGui/qscrollarea.h:56:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Width(const v8::Arguments& args);
                                                ^
../src/QtGui/qscrollarea.h:57:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Height(const v8::Arguments& args);
                                                 ^
../src/QtGui/qscrollarea.h:58:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> ObjectName(const v8::Arguments& args);
                                                     ^
../src/QtGui/qscrollarea.h:59:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetObjectName(const v8::Arguments& args);
                                                        ^
../src/QtGui/qscrollarea.h:60:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Parent(const v8::Arguments& args);
                                                 ^
../src/QtGui/qscrollarea.h:61:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Update(const v8::Arguments& args);
                                                 ^
../src/QtGui/qscrollarea.h:62:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetFocusPolicy(const v8::Arguments& args);
                                                         ^
../src/QtGui/qscrollarea.h:63:47: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Move(const v8::Arguments& args);
                                               ^
../src/QtGui/qscrollarea.h:64:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> X(const v8::Arguments& args);
                                            ^
../src/QtGui/qscrollarea.h:65:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Y(const v8::Arguments& args);
                                            ^
../src/QtGui/qscrollarea.h:68:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetWidget(const v8::Arguments& args);
                                                    ^
../src/QtGui/qscrollarea.h:69:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Widget(const v8::Arguments& args);
                                                 ^
../src/QtGui/qscrollarea.h:70:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetFrameShape(const v8::Arguments& args);
                                                        ^
../src/QtGui/qscrollarea.h:72:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     SetVerticalScrollBarPolicy(const v8::Arguments& args);
                                          ^
../src/QtGui/qscrollarea.h:74:44: error: ‘Arguments’ in namespace ‘v8’ does not name a type
     SetHorizontalScrollBarPolicy(const v8::Arguments& args);
                                            ^
../src/QtGui/qscrollarea.h:75:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> VerticalScrollBar(const v8::Arguments& args);
                                                            ^
../src/QtGui/qscrollarea.h:76:62: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> HorizontalScrollBar(const v8::Arguments& args);
                                                              ^
In file included from ../src/qt.cc:51:0:
../src/QtGui/qscrollbar.h:37:48: error: expected class-name before ‘{’ token
 class QScrollBarWrap : public node::ObjectWrap {
                                                ^
../src/QtGui/qscrollbar.h:49:28: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   QScrollBarWrap(const v8::Arguments& args);
                            ^
../src/QtGui/qscrollbar.h:52:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtGui/qscrollbar.h:55:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Value(const v8::Arguments& args);
                                                ^
../src/QtGui/qscrollbar.h:56:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> SetValue(const v8::Arguments& args);
                                                   ^
In file included from ../src/qt.cc:53:0:
../src/QtTest/qtesteventlist.h:37:52: error: expected class-name before ‘{’ token
 class QTestEventListWrap : public node::ObjectWrap {
                                                    ^
../src/QtTest/qtesteventlist.h:46:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                              ^
../src/QtTest/qtesteventlist.h:49:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> AddMouseClick(const v8::Arguments& args);
                                                        ^
../src/QtTest/qtesteventlist.h:50:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> AddKeyPress(const v8::Arguments& args);
                                                      ^
../src/QtTest/qtesteventlist.h:51:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
   static v8::Handle<v8::Value> Simulate(const v8::Arguments& args);
                                                   ^
qt.target.mk:117: recipe for target 'Release/obj.target/qt/src/qt.o' failed
make: *** [Release/obj.target/qt/src/qt.o] Error 1
make: Leaving directory '/home/osboxes/dev/node_modules/node-qt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/osboxes/dev/node_modules/node-qt
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN previewer@1.0.0 No repository field.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "node-qt"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt@0.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-qt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-qt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-qt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/osboxes/dev/npm-debug.log
```

**Comment by carlomilanesi** [comment]
I have the same error when I install with `npm install git://github.com/arturadib/node-qt.git`
on Mint 18.2. Also `sudo npm install node-qt` does not work.

**Comment by Solifugus** [comment]
The same exact issue of fully up-to-date Debian stable.  I really hope this project is being maintained.  Node and QT are a match made in heaven and I would so like to make us of it.  My C++ skills are very stale, as I haven't worked in it in at least 15 years... and never was a rock star.... but did a little C++ QT back then... It was love.
