### ISSUE TITLE
osX Mac failed on node-gyp rebuild

### ISSUE THREAD

**Issue by Vineetsai** [arturadib/node-qt#43]
Not able to use it on Mac, getting error on 'node-qpy rebuild' Also attached npm-build log.

node-gyp rebuild                                                                                                                        10:25:57
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.6.1 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/vineetsaini/.nvm/versions/node/v4.6.1/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vineetsaini/Documents/workspacenode/qtTest/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vineetsaini/.nvm/versions/node/v4.6.1/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/vineetsaini/.node-gyp/4.6.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/vineetsaini/.node-gyp/4.6.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/vineetsaini/.nvm/versions/node/v4.6.1/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/vineetsaini/Documents/workspacenode/qtTest',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/vineetsaini/Documents/workspacenode/qtTest) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/vineetsaini/.nvm/versions/node/v4.6.1/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/Users/vineetsaini/.nvm/versions/node/v4.6.1/bin/node" "/Users/vineetsaini/.nvm/versions/node/v4.6.1/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/vineetsaini/Documents/workspacenode/qtTest
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
[npm-debug.log.zip](https://github.com/arturadib/node-qt/files/569633/npm-debug.log.zip)

**Comment by Vineetsai** [comment]
Any update or anyone dealt with same issue using node-qt on mac?

**Comment by gabssnake** [comment]
Similar issue on versions:
- Node 8.11.3
- Node 6.14.4
- Node 4.9.1

MacOS High Sierra 10.13.6
