### ISSUE TITLE
Build fail OS X 10.11.6

### ISSUE THREAD

**Issue by ghost** [arturadib/node-qt#46]
```
$ npm install node-qt

> node-qt@0.0.2 install /Users/me/Desktop/node_modules/node-qt
> node-gyp rebuild

  CXX(target) Release/obj.target/qt/src/qt.o
../src/qt.cc:30:9: warning: 'BUILDING_NODE_EXTENSION' macro redefined [-Wmacro-redefined]
#define BUILDING_NODE_EXTENSION
        ^
<command line>:8:9: note: previous definition is here
#define BUILDING_NODE_EXTENSION 1
        ^
In file included from ../src/qt.cc:33:
In file included from ../src/QtCore/qsize.h:35:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/QSize:1:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qsize.h:45:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qnamespace.h:45:
../deps/qt-4.8.0/darwin/x64/include/QtCore/qglobal.h:328:6: warning: "This version of Mac OS X is unsupported" [-W#warnings]
#    warning "This version of Mac OS X is unsupported"
     ^
In file included from ../src/qt.cc:33:
../src/QtCore/qsize.h:37:32: error: expected class name
class QSizeWrap : public node::ObjectWrap {
                               ^
../src/QtCore/qsize.h:51:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:33:
../src/QtCore/qsize.h:54:44: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> Width(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:33:
../src/QtCore/qsize.h:55:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> Height(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:34:
../src/QtCore/qpointf.h:37:34: error: expected class name
class QPointFWrap : public node::ObjectWrap {
                                 ^
../src/QtCore/qpointf.h:48:21: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  QPointFWrap(const v8::Arguments& args);
                    ^~~~~~~~~~~~~
                    v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:34:
../src/QtCore/qpointf.h:51:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:34:
../src/QtCore/qpointf.h:54:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> IsNull(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:34:
../src/QtCore/qpointf.h:55:40: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> X(const v8::Arguments& args);
                                       ^~~~~~~~~~~~~
                                       v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:34:
../src/QtCore/qpointf.h:56:40: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> Y(const v8::Arguments& args);
                                       ^~~~~~~~~~~~~
                                       v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:36:
In file included from ../src/QtGui/qapplication.h:34:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/QApplication:1:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qapplication.h:45:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qcoreapplication.h:45:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qobject.h:50:
../deps/qt-4.8.0/darwin/x64/include/QtCore/qlist.h:184:22: error: reference to 'random_access_iterator_tag' is ambiguous
        typedef std::random_access_iterator_tag  iterator_category;
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note: candidate found by name
      lookup is 'std::__1::random_access_iterator_tag'
struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
                             ^
../deps/qt-4.8.0/darwin/x64/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
    struct random_access_iterator_tag;
           ^
In file included from ../src/qt.cc:36:
In file included from ../src/QtGui/qapplication.h:34:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/QApplication:1:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qapplication.h:45:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qcoreapplication.h:45:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qobject.h:50:
../deps/qt-4.8.0/darwin/x64/include/QtCore/qlist.h:231:22: error: reference to 'random_access_iterator_tag' is ambiguous
        typedef std::random_access_iterator_tag  iterator_category;
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:364:30: note: candidate found by name
      lookup is 'std::__1::random_access_iterator_tag'
struct _LIBCPP_TYPE_VIS_ONLY random_access_iterator_tag : public bidirectional_iterator_tag {};
                             ^
../deps/qt-4.8.0/darwin/x64/include/QtCore/qiterator.h:51:12: note: candidate found by name lookup is 'std::random_access_iterator_tag'
    struct random_access_iterator_tag;
           ^
In file included from ../src/qt.cc:36:
../src/QtGui/qapplication.h:36:39: error: expected class name
class QApplicationWrap : public node::ObjectWrap {
                                      ^
../src/QtGui/qapplication.h:45:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:36:
../src/QtGui/qapplication.h:48:52: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> ProcessEvents(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:36:
../src/QtGui/qapplication.h:49:43: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> Exec(const v8::Arguments& args);
                                          ^~~~~~~~~~~~~
                                          v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:37:
In file included from ../src/QtGui/qwidget.h:35:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/QWidget:1:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qwidget.h:49:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qpalette.h:47:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qbrush.h:53:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtGui/qpixmap.h:49:
In file included from ../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer.h:50:
../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer_impl.h:435:17: warning: 'register' storage class specifier is deprecated and incompatible
      with C++1z [-Wdeprecated-register]
                register int tmp = o->strongref;
                ^~~~~~~~~
../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer_impl.h:822:5: warning: 'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
    register X *ptr = static_cast<X *>(src.data()); // if you get an error in this line, the cast is invalid
    ^~~~~~~~~
../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer_impl.h:834:5: warning: 'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
    register X *ptr = dynamic_cast<X *>(src.data()); // if you get an error in this line, the cast is invalid
    ^~~~~~~~~
../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer_impl.h:846:5: warning: 'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
    register X *ptr = const_cast<X *>(src.data()); // if you get an error in this line, the cast is invalid
    ^~~~~~~~~
../deps/qt-4.8.0/darwin/x64/include/QtCore/qsharedpointer_impl.h:866:5: warning: 'register' storage class specifier is deprecated and incompatible with
      C++1z [-Wdeprecated-register]
    register X *ptr = qobject_cast<X *>(src.data());
    ^~~~~~~~~
In file included from ../src/qt.cc:37:
../src/QtGui/qwidget.h:64:34: error: expected class name
class QWidgetWrap : public node::ObjectWrap {
                                 ^
../src/QtGui/qwidget.h:73:42: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                         ^~~~~~~~~~~~~
                                         v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/qt.cc:37:
../src/QtGui/qwidget.h:76:45: error: no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
  static v8::Handle<v8::Value> Resize(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/me/.node-gyp/11.4.0/include/node/v8.h:143:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
7 warnings and 20 errors generated.
make: *** [Release/obj.target/qt/src/qt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/Desktop/node_modules/node-qt
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/me/Desktop/package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-qt@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-12-19T03_59_11_755Z-debug.log```

**Comment by 1AoB** [comment]
这个项目都十二年前了
