### ISSUE TITLE
Cannot install on Win10 64bit

### ISSUE THREAD

**Issue by Aaron2550** [arturadib/node-qt#47]
When trying to install nodq-qt i get

```
C:\WINDOWS\system32>npm install node-qt

> node-qt@0.0.2 install C:\WINDOWS\system32\node_modules\node-qt
> node-gyp rebuild


C:\WINDOWS\system32\node_modules\node-qt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\node-qt
gyp ERR! node -v v10.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-qt@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gray\AppData\Roaming\npm-cache\_logs\2019-08-11T15_29_47_557Z-debug.log

```
that mentioned log file is https://files.catbox.moe/zgnkl9.log

**Comment by angelhdzmultimedia** [comment]
### Hi!

Same here. Is there a fix or not yet?

**Comment by Aaron2550** [comment]
I think I know why, I forgot the -g flag. Try with that

**Comment by angelhdzmultimedia** [comment]
I tried it. Same error. And now I know it's because nodeqt doesn't support my Python version. I have **Python 3.7**.

**Comment by angelhdzmultimedia** [comment]
![image](https://user-images.githubusercontent.com/10191085/65326353-3c451280-db7f-11e9-9d11-09e5e74792e9.png)
