### ISSUE TITLE
Error: Cannot find module '...../node_modules/node-qt/lib/../build/Release/qt.node'

### ISSUE THREAD

**Issue by alessioalex** [arturadib/node-qt#8]
require('node-qt')
Error: Cannot find module '/Users/myuser/www/node_modules/node-qt/lib/../build/Release/qt.node'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/alexandruvladutu/www/node_modules/node-qt/lib/qt.js:40:10)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

What's up with that? I got that in Windows also, but I thought it would work on Mac :|

**Comment by alessioalex** [comment]
My bad, I was running node 0.6.12 and node-qt needs node >= 0.6.14
